# Generated by Django 4.0.6 on 2022-08-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlateNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_num', models.CharField(blank=True, max_length=100)),
                ('num', models.CharField(blank=True, max_length=100)),
                ('car_owner_name', models.CharField(blank=True, max_length=100)),
                ('telephone_num', models.CharField(blank=True, max_length=100)),
                ('trader_status', models.CharField(blank=True, max_length=100)),
                ('move_ability', models.CharField(blank=True, max_length=1)),
                ('exit_is_unrestricted', models.CharField(blank=True, max_length=1)),
                ('country', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
